### ISSUE TITLE
Can't talk to Lanette/Not able to pick up Pokemon

### ISSUE THREAD

**Issue by MitchBunks** [GearsProgress/Poke_Transporter_GB#11]
Hi, I think my english Pokemon Emerald save got into a glitched state. It started out pretty smooth, but then some weird stuff happened near the end of the transfer.

I was transferring from my english copy of Crystal, and it linked up just fine. I wanted to transfer over my shiny Lugia and Ho-oh (after around +50 hours lol). It was able to see them just fine, but then this is where things got weird... The names were all random characters, but everything else looked fine with them. I was hoping this was just a visual glitch, but when I confirmed, usually the GBC game is supposed to reset itself after a completed transfer, but this did not, it stayed on the transferring screen until I reset the game, and I made the discovery that they were **not** gone from my Crystal game thankfully. But then I checked out my Emerald game and went to talk to Lanette, she didn't say her special dialogue she would usually say to give the transferred Mons... So I decided to try the transfer again, but this time with a different cable, I'm no longer able to transfer because it says I haven't picked my Mons yet...

So now I'm here, hoping that if I provide my save file, that maybe you could look at it? Keep in mind, I'm still able to play the game normally, just not able to use the tool anymore.

Any help will be greatly appreciated!

**Comment by PizzaTimeJoshua** [comment]
The location to pick up the Pokemon has been updated. In Emerald it’ll be southeast of the Pokemon Center in Sootopolis.

**Comment by MitchBunks** [comment]
Oh good! Thank you so much! This was it!

**Comment by GearsProgress** [comment]
Glad you got it figured out! The glitched names aren't supposed to happen (obviously lol). I want to try and figure out what went wrong:

- Did you start a transfer, cancel it, and then do another transfer without reloading the program?
- Were the names of the Pokemon still glitched when you received them in Emerald?

**Comment by mitchellbunkers** [comment]
No, the transfer was a clean start, both Crystal and PT. And yeah, the names of the pokemon were still glitched after transfer, and even a hidden Parasect that I didn't see when confirming the transfer. Something I will say is that I did do a transfer with Silver as well, just to make sure it wasn't the mons that were glitched or something. And that worked perfectly, no glitched names or anything like what happened with Crystal. I'll try and perform the transfer again with Crystal and provide screenshots/footage this time. But other than that, I love this tool!

**Comment by GearsProgress** [comment]
Thanks for the confirmation!! That's really strange that it would specifically have issues with the nicknames and not anything else... I'll definitely do some more research and see what happened- this isn't the only time this issue has come up.
