### ISSUE TITLE
Suggestion: Specify Location of Pick Up

### ISSUE THREAD

**Issue by PizzaTimeJoshua** [GearsProgress/Poke_Transporter_GB#12]
When you try and transfer the Pokemon to the GBA, Fennel mentions where you need to pick up the Pokemon briefly after the transfer happens.
_However_, if your like me, you might have accidently mashed through the message, or forgot where she said.

I think it would be helpful for Fennel to remind you where to go if you try and transfer another Pokemon. Like when she says, "It looks like still have Pokemon to pick up." You can add in, "You can find them at XXX."

I know people who used the previous versions or missed the message might be confused where to go without looking it up online.

If possible, you could also have the location text a different color to emphasize where the pick up location is.

**Comment by GearsProgress** [comment]
That's totally something I thought about and just straight up forgot to implement lol- thank you!! That'll be part of one of the next releases :)
