### ISSUE TITLE
Silver Glitched Mantine + Save / Daycare Bad EGG 

### ISSUE THREAD

**Issue by YanmaSuperfan** [GearsProgress/Poke_Transporter_GB#13]
Hi, I'd like to say that this program(?) is AMAZING! When replaying the old GB games, I found out about it at 0.2.4 so it inspired me to finally make a Gen 3 living dex (Only missing Huntail now!). When I was ready to use it, 1.0.1 had just been released and low and behold it worked flawlessly for Yellow {ENG} to Sapphire {ENG}. Silver on the other hand has a few issues.

**Bugged Mantine**
(Images below also explain)   When transferring the 4th box (Scizor to Phanpy in National dex order) the program kept glitching out by having the first and last Pokémon on the top row have their names start with a ? and a Magcargo with a completely glitched name "n8e", it would later stop right at Mantine who'd be level 0 even though there were still pokémon in the box they wouldn't appear.

I'd later find out Mantine was the glitched one after trying to send it over and it still showed level 0. My fix for it was to use a rare candy (I was also going to try to deposit it into daycare and grab it again but this worked first) to bump it up from 22 -> 23.

My guess would be either its exp or stats didn't play well with the program so I'll attach it as well.

**The save file is corrupt!**
I'm unsure why, but my Silver {ENG} would always get corrupt after transferring to Sapphire {ENG}, and the colour plate also was borked, [Looked similar like this](https://bulbapedia.bulbagarden.net/wiki/Glitch_dimension). I was using V1.0.1 so you might have fixed this already. Sorry if this isn't an issue still!

**Daycare Bad EGG**

In Sapphire {ENG} my first Pokémon at the daycare (was a Roselia if it matters) was replaced with a bad EGG, I have no clue how or when this happened as I transferred a lot over. The way I dealt with it was to place it in a box and overwrite the slot in PkHex with a random pokémon, the weirdest thing about that though is that it did not show up in PkHex at all and when I wrote over it, the game merged the two with the Deoxes being level 0 and stuff, luckily I could release it and so far it's been good!

**Tidbit of Knowledge**

The GBA cable CAN be used (in theory)! I've yet to try it with this but in other GB games, you can connect two GBA cables with the purple ends being connected via the bricks and the grey ends going into the GBA systems, the GB(C) can't use it though as the cable doesn't fit.

Sorry if this isn't a very good Issue, I've never really opened one before or frankly used this site beyond downloading a release of something :)

![image](https://github.com/user-attachments/assets/01c62547-7dd0-4ab4-ab9d-6b6958bc1036)
![6](https://github.com/user-attachments/assets/328636c0-86b7-43bf-a820-71ad3fdd4f97)
![5](https://github.com/user-attachments/assets/5367e2d3-e2f5-4e94-97a6-ac04e8f17cb4)
![4](https://github.com/user-attachments/assets/c1369617-dded-47eb-bb38-1d1a2ab24f78)
![3](https://github.com/user-attachments/assets/b9266e8a-e96c-4f76-b133-cd6a937d21d3)
![2](https://github.com/user-attachments/assets/0d98657e-9ac5-480d-9faf-1cf126a45157)
![1](https://github.com/user-attachments/assets/8b759429-5a45-4667-9925-36ae004190a3)

**Comment by GearsProgress** [comment]
Hi there!! Sorry about the late response!

I believe that this issue was fixed in v1.0.2, but you'd have to test it again to be sure. The Bad Egg in the daycare is *really* weird though, I haven't heard of that happening before... I'll have to double check on that and make sure I'm not accidentally writing to that area of the save file.

Also- don't feel bad, this was a perfect way to post an issue! I was a bit stressed when first using GitHub, but I promise none of us will bite :) . Thank you so much for all the good information, this will legitimately be very helpful in the development of this program!!

**Comment by GearsProgress** [comment]
Jumping back to this thread to say that if this bug wasn't fixed already in v1.0.2, it should be once v1.0.3 comes out. I'd imagine these issues stem from the same thing I discussed in this issue thread:

https://github.com/GearsProgress/Poke_Transporter_GB/issues/9
