### ISSUE TITLE
Writing tool in repro carts 

### ISSUE THREAD

**Issue by kazzaluis** [GearsProgress/Poke_Transporter_GB#14]
I have 2 repro cards with this PCB both has 1mb flash save memory

I wrote the clean tool in this and I have a repro game with the same PCB with a fire red room in

The tool will work fine or will crash o bad saving file 

Tbh I don't have cable link and other gba to thest it

**Comment by GearsProgress** [comment]
I would not recommend using the program with repo carts, as there is no guarantee that it will work due to there being a wide breadth of carts and how they all work differently.
