### ISSUE TITLE
Using a repro cart for the GB Transporter rom

### ISSUE THREAD

**Issue by klchidester8** [GearsProgress/Poke_Transporter_GB#15]
I wrote the GB Transporter rom to a reproduction cart. It boots up just fine and it seems to write to the RAM just fine because I can pull out the cartridge and put in a legit copy of Ruby and the program still runs. However, It will not communicate with the Gen 3 cart in the GBA or the Gen 1 cart in the GBC over link cable. Not sure what I am doing wrong here.

It seems like it defaults to thinking that I am connected to a Leaf Green cartridge (I think this because of the green background) and it gives a list of Pokémon that are not my own.

I am not sure what I am doing wrong.

Attached is a picture of the list of Pokémon. Its not connected to another Gameboy in this picture but it does the same thing whether it is or isn't. 
![20240909_120446](https://github.com/user-attachments/assets/a96c901b-adf6-44e9-94d6-eeff5952696b)

**Comment by GearsProgress** [comment]
Sorry for the late response!!

This is really interesting, because that's the debug mode I use (assuming LeafGreen and sending over those Pokemon)... did you download the latest release, or did you manually build my latest push?

**Comment by klchidester8** [comment]
I am new to this whole thing. So maybe I did something wrong.
I downloaded the repository as a zip, unzipped, and then used "make" through the terminal to create the gba rom.
Was that right?

**Comment by GearsProgress** [comment]
Ah! That's how the source code is compiled into the GBA ROM- so in a way yes, that is right. However, my pushes to the repository aren't release ready (ie, having debug more enabled), so you're better off downloading the GBA file directly in the releases section (https://github.com/GearsProgress/Poke_Transporter_GB/releases). Hopefully that works a bit better!! 😄

**Comment by klchidester8** [comment]
Well that worked. However, as a side note, it did not work with the Funny Playing GBC. It had to be original nintendo hardware. However, I have that too so it wasn't a problem.

Thank you so much!

**Comment by GearsProgress** [comment]
Glad to see that it worked!! Enjoy! :D
