### ISSUE TITLE
Recommended Flashcart

### ISSUE THREAD

**Issue by PhotexMedia** [GearsProgress/Poke_Transporter_GB#18]
Hey There @GearsProgress!

Incredibly impressive project and really loved the background on your website in the creation of this tool, as someone (as many others I imagine) I'm trying to do this in the cheapest and SAFEST way possible. It looks like the only requirement for a flashcart is multiboot compatibility, is there a recommended list of flashcart models that you have tested throughout your development or even just a "Just buy X" comment is totally valid as well no matter the cost.

**Comment by SilverTheShinyEevee** [comment]
As far as I'm aware, you can use any GBA flashcart, *but* the EZ-flash Omega is (at least I'm my opinion) the easiest to work with. You just need to boot the GBA in multiboot mode by holding L when the GBA boots up.

**Comment by mkiisoft** [comment]
I'm using Everdrive 5x (regular size) and works perfectly on my Analogue Pocket. I run the "game" (app) as any other one, wait for the loading screen, press start and will ask you to swap the cartridge, once swapped, press A. Change your Everdrive 5x to an actual GBA Pokemon game and works.

**Comment by GearsProgress** [comment]
As others have said, any flashcart should work- but the EZ-Flash Omega is the one that I personally use and test with. If you have a Wii with homebrew and a GBA/GCN Link Cable, you can also upload the ROM through that!
