### ISSUE TITLE
Competition hall paintings corruption.

### ISSUE THREAD

**Issue by cubeyz** [GearsProgress/Poke_Transporter_GB#20]
I'm not sure if this has come up before because I'm sure people don't really think about competitions. 
But anyway, I noticed my trainer card on Ruby had gone down from 4* to 3*, I was rather confused about this and in my research I found the paintings in the competition hall now crash the game.

After this to confirm the cause, I got a save back up from a time before I did the transfer with my 4* trainer card. After doing another transfer from Red to Ruby I can confirm that again, the paintings are corrupted and my trainer card is 3*.
I'm not aware if it does anything negative in the non Hoenn games, or GB but I haven't really looked much on those. This one just kind of jumped out the most.

**Comment by GearsProgress** [comment]
This is really strange, thank you for bringing it to my attention!! Do you happen to have a way to send me your save files so I can take a look at the raw save data?

**Comment by GearsProgress** [comment]
Ah- I figured out the problem! Ruby and Sapphire were trying to add Wonder Card save data despite not being in those games. The bug will be fixed in the next release! Thank you again for bringing this to my attention :)

**Comment by cubeyz** [comment]
Cool! I was just about to send my saves but I guess I don't have too, glad you found it.
