### ISSUE TITLE
I cannot pickup Pokemon from Lanette

### ISSUE THREAD

**Issue by TDO2024** [GearsProgress/Poke_Transporter_GB#23]
Hello everyone,

I succesfully transferred Pokemon from English Pokemon Yellow on an English Pokemon Emerald. The Pokémon on yellow are disappeared correctly but on my Pokemon Emerald I cannot pickup the Pokemon by Lanette because she don't speak an other text. I cannot transfer again until I pickup the Pokemon.

What can I do?

Thank you so much!

**Comment by GearsProgress** [comment]
Hello!! As of version 1.0.0, Pokemon transferred to Emerald will be picked up in the house south east of Sootopolis City! Sorry for the confusion!

Let me know if you have any other issues :D

**Comment by TDO2024** [comment]
> Hello!! As of version 1.0.0, Pokemon transferred to Emerald will be picked up in the house south east of Sootopolis City! Sorry for the confusion!
> 
> Let me know if you have any other issues :D

Ahhhh I get it!
Thank you very much :)
