### ISSUE TITLE
Problem with GBA LINK CABLE ROM Sender v1.2 by FIX94

### ISSUE THREAD

**Issue by VITORVIDEIRA** [GearsProgress/Poke_Transporter_GB#28]
Hi,
So with the latest update to version 1.1.0, it seems that the GBA file is not recognized. I'm using the Wii method with the Homebrew Channel, Wii Mod Lite, and GBA Link Cable ROM Sender v1.2. I've checked, and the files are in the correct folder (/gba). I’ve tried with the previous version, and it works. I've also tested both versions on a GBA emulator, and both seem to be fine.

**Comment by GearsProgress** [comment]
Hey there! Just wanted to confirm that the problem was solved when the issue was closed- sorry it took so long to get back to you!!

**Comment by VITORVIDEIRA** [comment]
Hey! My bad, sorry! I realized I just needed to right-click on the Wii Mod Lite interface to access version 1.1.0. Everything's all good now! Thank you for this project and for being so supportive :)
