### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by Aurareus** [GearsProgress/Poke_Transporter_GB#6]
Just a little nitpick, there's an extra word typo in the first sentence:
"Poké Transporter GB is a transfer tool **for created to** transfer Pokémon from..."
Should be:
"Poké Transporter GB is a transfer tool created to transfer Pokémon from..."
or
"Poké Transporter GB is a transfer for transfering Pokémon from..."

**Comment by GearsProgress** [comment]
Ah- nice catch! Thank you!! :D
